version: '3'
services:
  postgresql:
    image: postgres:14.4
    env_file:
      - .env_docker
    ports:
      - "5444:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  postgresql_test:
    image: postgres:14.4
    env_file:
      - .env_test
    ports:
      - "5445:5432"
volumes:
  postgres-data: {}