"""UserTable
Revision ID: 54a654b17512
Revises: 
Create Date: 2023-06-06 18:59:56.877418
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '54a654b17512'
down_revision = None
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cell', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_street', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_street_number', sa.Integer(), nullable=False),
    sa.Column('location_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_postcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###